        /*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //设置：
	'Options': '设置',
    'Preferences': '首选项',
    'Draw': '抽卡',
    'Import': '导入',
    'Number Format': '数字格式',
    'Change the verb associated with drawing cards, in places such as the game title and item descriptions.': '更改与抽卡相关的动画，例如在游戏标题和物品描述等地方',
    'Default': '默认',
    'Scientific': '科学计数法',
    'Engineering': '工程计数法',
    'SI Prefixes': '科学词头',
    'Alphabet': '字母表',
    'Chinese': '中文计数法',
    'Korean': '韩语计数法',
	'Verb': '动画',
    'Pull': '拉取',
    'Change the verb associated with pulling cards, in places such as the game title and item descriptions.': '更改与卡牌拉取相关的动画，例如在游戏标题和物品描述等位置',
    'Summon': '召唤',
    'Change the verb associated with summoning cards, in places such as the game title and item descriptions.': '更改与卡牌召唤相关的动画，例如在游戏标题和物品描述等位置',
    'Roll': '滚动',
    'Change the verb associated with Rolling cards, in places such as the game title and item descriptions.': '更改与卡牌滚动相关的动画，例如在游戏标题和物品描述等位置',
    'Spin': '旋转',
    'Change the verb associated with Spinning cards, in places such as the game title and item descriptions.': '更改与卡牌旋转相关的动画，例如在游戏标题和物品描述等位置',
    'Gacha': '扭蛋',
    'Change the verb associated with gacha\'ing cards, in places such as the game title and item descriptions.': '更改与卡牌扭蛋相关的动画，例如在游戏标题和物品描述等位置',
    'Card Images': '卡牌图像',
	'Background Music': '背景音乐',
    'Disabled': '禁用',
    'Enabled': '启用',
    'Save Management': '存档管理',
    'Local Save': '本地存档',
    '(last saved': '(最近保存于',
    'ago)': '前)',
    '(game saved)': '(游戏进度已保存)',
    'Game saved': '游戏进度已保存',
    'It is now safe to close this tab.': '现在可以安全地关闭此标签页',
    '(Note: this game auto-saves after a minute since the last save and on certain events such as after a draw and when a setting is changed)': '(注意：本游戏会在上次保存后经过一分钟自动保存，并在特定事件发生时进行自动保存，例如抽牌后或更改设置时)',
    'Close': '关闭',
    'Manual Save': '手动存档',
    'Import/Export Save': '导入/导出存档',
    'Hard Reset': '硬重置',
    'The text box below contains your save data. Copy your save and keep it somewhere safe.': '下方的文本框包含您的存档数据。请复制存档并妥善保存',
    'Alternatively, paste your save there and press "Import from Text Box" to load the save.': '或者，将您的存档粘贴到此处，然后点击“从文本框导入”以加载存档',
	'Copy to Clipboard':'复制到剪贴板',
	'Download File':'下载存档文件',
	'Import from Text Box':'从文本框导入',
	'Upload File':'上传存档文件',
	'Import this save?':'导入此存档？',
	'Copied':'已复制',
	'Save data copied to clipboard.':'存档数据已复制到剪贴板',
	'Would you like to import this save? Your current game will be overridden!':'您确定要导入此存档吗？当前游戏进度将被覆盖！',
	'Time played:':'游玩时间：',
	'Cards drawn:':'已抽取卡牌：',
	'Keep preferences':'保留偏好设置',
	'(Note: preferences that are bound to an unlockable will be changed to a different one\n                if said unlockable is not present in the new save)':'(注意：与可解锁内容绑定的偏好设置将在新存档中缺失该解锁内容时更改为其他设置)',
	'No, go back':'不，返回',
	'Yes, import save':'是，导入存档',
	'Really hard reset?':'确定要硬重置？',
	'This action will':'此操作将会',
	'COMPLETELY WIPE YOUR SAVE CLEAN.':'彻底清除您的存档。',
	'You\'ll go back to the very beginning \n                    of the game with':'您将回到游戏的最初状态，并且',
	'NO BONUSES IN RETURN.':'不会获得任何奖励。',
	'The game will copy the current save data to your clipboard in case you change your mind.':'游戏将把当前存档数据复制到您的剪贴板，以防您改变主意',
	'(Note: preferences that are bound to an unlockable will be changed to a different one)':'(注意：与可解锁内容绑定的偏好设置将被更改为其他设置)',
	'Yes, hard reset':'是，硬重置',
	'Other':'其他',
	'Info':'信息',
	'About & Credits':'关于与鸣谢',
	'Other other':'其他类别',
	'johnvertisement':'John 广告',
	'(Note: links open in this tab, ctrl+click to not accidentally close the game)':'(注意：链接将在当前标签页打开，按住 Ctrl 并点击可避免意外关闭游戏)',
	'Game by':'游戏制作',
	'One Trillion':'一万亿次',
	'Free Draws':'免费抽卡次数',
	'(because we can\'t help ourselves from advertising free draw counts)':'(因为我们忍不住要宣传免费的抽卡次数)',
	'(and you thought a-thousand-ish was too much)':'(你还以为大约一千次已经太多了呢)',
	'(no-download game with cutting-edge web technologies)':'(无需下载的游戏，采用前沿的 Web 技术)',
	'(look ma, i\'m in a <marquee> tag!)':'(看啊，妈！我在一个 <marquee> 标签里！)',
	'(because we can\'t help ourselves from inflating free draw counts)':'(因为我们忍不住要夸大免费的抽卡次数)',
	'(about as generous a gacha game could be)':'(几乎是抽卡游戏能达到的最大慷慨程度)',
	'Used libraries:':'使用的库：',
	'Music by':'音乐制作',
	'(hey that\'s me)':'(嘿，那是我！)',
	'Icons from various sources via':'图标来自多个来源，通过',
	'(would the game count as parody and thus eligible for fair use?':'(该游戏是否算作恶搞，因此符合合理使用原则？',
	'idk, i\'m not a lawyer)\n                    ':'不知道，我又不是律师)\n                    ',
	
	//收藏-主要
	'Collection':'收藏',
	'You\'ve got':'你获得了',
	'free':'免费',
	'draws':'抽卡次数',
	'Points':'点数',
	'Cards':'卡牌',
	'Shreds':'碎片',
	'Continue':'继续',
	'“Remains of excess cards, reduced to atoms. These cards almost have no trade value (except for the few':'“多余卡牌的残骸，被分解至原子级。这些卡牌几乎没有交易价值（除了部分',
	'cards), so people are inventing new ways to use them, such as shredding them to use as a new upgrade currency“':'卡牌）因此人们正在发明新的用途，比如将其粉碎后作为新的升级货币”',
	'Bulk Energy':'大宗能量',
	'“Used as Omega Cards\' loyalty program currency to allow you to trade multiple cards at once“':'“用作《Omega Cards》忠诚计划的货币，允许你一次性交换多张卡牌”',
	'In cooldown':'正在冷却中',
	'(you have':'(你持有',
	'(you\'ve drawn':'(你已抽取',
	'until cap)':'后到达上限)',
	'efficiency)':'效率)',
	'Upgrade':'升级',
	'Fusion':'融合',
	'Can\'t upgrade':'无法升级',
	'Can\'t fuse':'无法融合',
	'Can\'t purchase':'无法购买',
	'stars)\n                        (level':'星)\n                        (等级',
	'stars)\n                    (level':'星)\n                    (等级',
	'stars)\n                        ':'星)\n                        ',
	'stars)\n                    ':'星)\n                    ',
	'extra copies)':'额外副本)',
	'\n                        \n                        (crowned card)\n                        ':'\n                        \n                        (加冕卡)\n                        ',
	'\n                    \n                    (crowned card)\n                    ':'\n                    \n                    (加冕卡)\n                    ',
	'(card not yet owned)':'(尚未持有的卡)',
	'(fire faction)\n                        (':'(火系阵营)\n                        (',
	'“The world\'s most generic currency. It is generic enough to be assigned any use case imaginable“':'“世界上最通用的货币。它通用到可以被赋予任何 imaginable 的用途”',
	'“Produced for the almighty Omega Cards game, these cards are actually vouchers for you to spend more money to draw more cards... after you use up all your one trillion free card draws, at least. They are too happy about giving people trillions of free card draws, in fact, everyone are“':'“为全能的《Omega Cards》游戏制作，这些卡片实际上是让你花更多钱抽更多卡的凭证……至少是在你用完一万亿次免费抽卡次数之后。事实上，他们非常乐于提供数万亿次免费抽卡次数，实际上，每个人都...”',
	'Click this big \"Draw\" button below to start':'点击下方这个大大的“抽卡”按钮开始吧！',
	'drawing':'抽取',
	'some of them!':'其中的一些卡牌！',
	'Cards left':'剩余卡牌',
	'Seems like there isn\'t anything here...':'似乎这里空无一物……',
	'Upgrade cost:':'升级费用：',
	'Fusion cost:':'融合费用：',
	'Purchase cost:':'购买费用',
	'Click to upgrade.':'点击升级',
	'Click to fusion.':'点击融合',
	'Click to purchase.':'点击购买',
	'Insufficient copies.':'副本不足',
	'Insufficient Points.':'点数不足',
	'Insufficient Shreds.':'碎片不足',
	'Insufficient Fire Power.':'火焰能量不足',
	'Insufficient Water Power.':'水源能量不足',
	'Insufficient Leaf Power.':'植物能量不足',
	'Insufficient Sun Power.':'太阳能量不足',
	'Insufficient Moon Power.':'月亮能量不足',
	'This card can not be fused.':'此卡无法融合',
	'This card can not be upgraded.':'此卡无法升级',
	'Any rarity':'任何稀有度',
	'cards':'卡牌',
	'Any faction':'任何阵营',
	'No faction':'无阵营',
	'Fire faction':'火焰阵营',
	'Water faction':'水源阵营',
	'Leaf faction':'植物阵营',
	'Sun faction':'太阳阵营',
	'Moon faction':'月亮阵营',
	
	//阵营系统
	'Fire Power':'火焰能量',
	'Water Power':'水源能量',
	'Leaf Power':'植物能量',
	'Sun Power':'太阳能量',
	'Moon Power':'月亮能量',
	'(fire faction)':'(火焰阵营)',
	'(water faction)':'(水源阵营)',
	'(leaf faction)':'(植物阵营)',
	'(sun faction)':'(太阳阵营)',
	'(moon faction)':'(月亮阵营)',
	'(fire faction)\n                        (':'(火焰阵营)\n                        (',
	'(water faction)\n                        (':'(水源阵营)\n                        (',
	'(leaf faction)\n                        (':'(植物阵营)\n                        (',
	'(sun faction)\n                        (':'(太阳阵营)\n                        (',
	'(moon faction)\n                        (':'(月亮阵营)\n                        (',
	'“Power from the fire faction. Some consider discovering this humans\' greatest achievement“':'“来自火焰阵营的力量。有些人认为发现这一点是人类最大的成就”',
    '“Power from the leaf faction. You feel yourself to be one with nature“':'“来自植物阵营的力量。你感到自己与大自然融为一体”',
    '“Power from the moon faction. Also believed to also have the power to control earth“':'“来自月亮阵营的力量。也被认为具有控制地球的能力”',
    '“Power from the sun faction. Also believed to also have the power to control air“':'“来自太阳阵营的力量。也被认为具有控制空气的能力”',
    '“Power from the water faction. Always reminds you to keep yourself hydrated“':'“来自水阵营的力量。时刻提醒你保持水分”',
	'Switch to no faction':'切换到无阵营',
	'Switch to fire faction':'切换到火焰阵营',
	'Switch to water faction':'切换到水源阵营',
	'Switch to leaf faction':'切换到植物阵营',
	'Switch to sun faction':'切换到太阳阵营',
	'Switch to moon faction':'切换到月亮阵营',
	
	//卡牌 - N级
	'The Nothing Square':'虚无广场',
	'\"The Nothing Square\" ':'\"虚无广场\" ',
	'“That one square that is programmed to be picked 99% of the time“':'“那个被编程设定为99%时间内都会被选中的方格”',
	'A Single Point':'一积分',
	'\"A Single Point\" ':'\"一积分\" ',
	'“ここにいる“':'“在这里”',
	'Half A Point':'半个积分',
	'Half a Point':'半个积分',
	'\"Half A Point\" ':'\"半个积分\" ',
	'“To explain what half a point even is, we\'ll need to talk about parallel universes-“':'“为了解释什么是半个积分，我们需要谈谈平行宇宙——”',
	'Card Pack':'卡包',
	'\"Card Pack\" ':'\"卡包\" ',
	'“Well, if you want to use up all of those one trillion card draws you\'ll need to start drawing multiple of them at once, you know?“':'“嗯，如果你想用完那一万亿次抽卡，你得开始一次抽多个，知道吗？”',
	'Self-Filling Pack':'自填卡包',
	'\"Self-Filling Pack\" ':'\"自填卡包\" ',
	'“Incremental games, also known as idle games“':'“增量游戏，也叫做放置游戏”',
	'Bigger Wrap':'更大的包装',
	'\"Bigger Wrap\" ':'\"更大的包装\" ',
	'“You can idle for real this time“':'“这次你可以真正地放置游戏了”',
	'Scissors':'剪刀',
	'\"Scissors\" ':'\"剪刀\" ',
	'“If you haven\'t noticed it yet, you can click the pack while it\'s breaking to break it faster“':'“如果你还没注意到，你可以在卡包拆封时点击它，这样可以加速拆封过程”',
	'Fast Delivery':'快速配送',
	'\"Fast Delivery\" ':'\"快速配送\" ',
	'“Restock faster with our new fast delivery service—applied to all orders 1 card and above!“':'“通过我们的新快速配送服务更快补货——适用于所有1张卡及以上的订单！”',
	'In-Game Shop':'游戏商店',
	'\"In-Game Shop\" ':'\"游戏商店\" ',
	'“Find cards that can\'t be found from drawing, and probably spend all of your money trying to out-bid the highest bidder“':'“找到无法通过抽卡获得的卡牌，并可能会花光所有的钱，试图超越最高出价者”',
	
	//卡牌 - R级
	'Epic Shredding Machine':'史诗级粉碎机',
	'\"Epic Shredding Machine\" ':'\"史诗级粉碎机\" ',
	'“Instead of using a small office-made shredder, why not use the giant ones made for ASMR videos on the internet?“':'“与其使用小型办公室粉碎机，为什么不使用那些专为互联网上的ASMR视频制作的巨型粉碎机呢？”',
	'Amazing Shredding Moments':'惊人的粉碎时刻',
	'\"Amazing Shredding Moments\" ':'\"惊人的粉碎时刻\" ',
	'“Apparently people on the internet love watching things being shredded to pieces! You figure out you could record your Epic Shredding Machines shredding cards and upload it to PipeTube to earn some sweet, sweet ad revenue in the process“':'“显然，互联网上的人们喜欢看东西被粉碎成碎片！你意识到可以录下你的史诗级粉碎机粉碎卡牌视频，并将其上传到PipeTube，从中赚取一些丰厚的广告收入”',
	'Point Multiplier':'点数倍率',
	'\"Point Multiplier\" ':'\"点数倍率\" ',
	'“Every incremental game needs exponential growth, a generic currency needs a generic multiplier upgrade“':'“每个增量游戏都需要指数级增长，一个通用货币需要一个通用的倍率升级”',
	'Money Press':'钱币压制机',
	'\"Money Press\" ':'\"钱币压制机\" ',
	'“Press some of your shreds into money. This is precisely how legal money are made too, people won\'t even be able to notice a difference“':'“将一些碎片压制成钱。这正是合法货币的制造方式，人们甚至不会察觉出任何差异”',
	'Bulkier Card Packs':'更大批量的卡包',
	'\"Bulkier Card Packs\" ':'\"更大批量的卡包\" ',
	'“The bulkier, the better“':'“越大越好”',
	'Card Opener Factory':'卡包开启工厂',
	'\"Card Opener Factory\" ':'\"卡包开启工厂\" ',
	'“Produces large quantity of card openers“':'“生产大量卡包开启器”',
	'Recycling':'回收',
	'\"Recycling\" ':'\"回收\" ',
	'“Reusing cards to open more cards is a good idea actually“':'“重新利用卡牌来开启更多卡牌其实是个好主意”',
	'Composter':'堆肥机',
	'\"Composter\" ':'\"堆肥机\" ',
	'“Recycle even harder with this composter designed to make a metric-scrap-ton of cards“':'“使用这个堆肥机进行更强力的回收，它被设计用来制作大量的卡牌”',
	'Endurance Training':'耐力训练',
	'\"Endurance Training\" ':'\"耐力训练\" ',
	'“The card packs got some endurance training! Now they are harder to break into, but the contents are increased!“':'“卡包进行了耐力训练！现在它们更难打开，但内容物增加了！”',
	'System 2':'系统 2',
	'“Erm ackstually 🤓“':'“额，实际上 🤓”',
	
	//卡牌 - 阵营
	'Trending':'火焰蔓延',
	'\"Trending\" ':'\"火焰蔓延\" ',
	'“ah,':'“啊，',
	'that\'s hot,':'那太火了',
	'..., that\'s hot“':'……那太火了”',
	'Ocean':'海洋',
	'\"Ocean\" ':'\"海洋\" ',
	'“i\'m blue da be dee da be die“':'“我是蓝色哒嘀哒嘀哒哒嘀”',
	'Forest':'森林',
	'\"Forest\" ':'\"森林\" ',
	'“team trees ftw“':'“团队树木，必胜！”',
	'Air':'空气',
	'\"Air\" ':'\"空气\" ',
	'“feel the breath“':'“感受呼吸”',
	'Earth':'地球',
	'\"Earth\" ':'\"地球\" ',
	'“it is our home“':'“它是我们的家园”',
	'Fire Power Mastery':'火焰能量精通',
	'Water Power Mastery':'水源能量精通',
	'Leaf Power Mastery':'植物能量精通',
	'Sun Power Mastery':'太阳能量精通',
	'Moon Power Mastery':'月亮能量精通',
	'\"Fire Power Mastery\" ':'\"火焰能量精通\" ',
	'\"Water Power Mastery\" ':'\"水源能量精通\" ',
	'\"Leaf Power Mastery\" ':'\"植物能量精通\" ',
	'\"Sun Power Mastery\" ':'\"太阳能量精通\" ',
	'\"Moon Power Mastery\" ':'\"月亮能量精通\" ',
	'“Yes, these':'是的，这些',
	'cards really are just copy and paste, you don\'t think every gacha game does this all the time?“':'卡牌真的只是复制粘贴，你不会以为每款抽卡游戏都总是这样做吧？',
	
	//卡牌 - SR级
	'Perfectly Generic Card':'完美通用卡',
	'\"Perfectly Generic Card\" ':'\"完美通用卡\" ',
	'“A perfectly generic card that boosts the perfectly generic currency, the genericness is getting too perfect to handle“':'“一张完美通用的卡片，能够提升完美通用货币，这种通用性已经完美到难以承受的地步”',
	'A Pair of Points':'一对点数',
	'\"A Pair of Points\" ':'\"一对点数\" ',
	'“Two is always better than one“':'“2总是比1好”',
	'Dice Extractor':'骰子提取器',
	'\"Dice Extractor\" ':'\"骰子提取器\" ',
	'“Let the pips on the die guide you“':'“让骰子的点数指引你”',
	'Card Warehouse':'卡片仓库',
	'\"Card Warehouse\" ':'\"卡片仓库\" ',
	'“At this rate you will need to get yourself a bigger room just so you can store all your cards“':'“照这样下去，你可能需要给自己弄个更大的房间，才能放下你所有的卡牌”',
	'Obsessive-Compulsive':'强迫症',
	'Unlock the ability to filter cards by some criteria.':'解锁按条件筛选卡牌的功能',
	'“Must... keep it... organized...“':'“必须……保持……井井有条……”',
	
	//卡牌 - SSR级
	'Homestretch':'最后阶段',
	'\"Homestretch\" ':'\"最后阶段\" ',
	'“Thank you for going this far into the game! If you like it be sure to leave a like and subscribe for more content like this“':'“感谢你玩到这游戏的后期！如果你喜欢这款游戏，别忘了点个赞并订阅，以获取更多类似的内容！”',
	'Extra Points':'额外点数',
	'\"Extra Points\" ':'\"额外点数\" ',
	'“More points doesn\'t hurt, right?“':'“多点总没坏处，对吧？”',
	'Royal Junk':'皇家垃圾',
	'\"Royal Junk\" ':'\"皇家垃圾\" ',
	'“More valuable than regular junk“':'比普通垃圾更有价值',
	
	//卡牌 - EX级
	'StackRAR':'堆叠压缩',
	'“Please note that StackRAR is not a free card. After a 40 day trial period you must either buy a license or burn this card off of your collection“':'“请注意，’堆叠压缩‘不是一张免费卡。在40天的试用期后，您必须购买许可证或将此卡从您的收藏中销毁”',
	'Shredder':'碎纸机',
	'“Act as if nothing has ever happened“':'“表现得好像什么都没发生过”',
	'Overused Faction System':'过度使用的阵营系统',
	'Unlock Factions. Use factioned draws to get factioned currencies and faction-specific cards. (Factioned currency has a rare chance to appear.)':'解锁阵营。使用阵营抽卡获取阵营货币和阵营专属卡牌（阵营货币有稀有几率出现。）',
	'“Long ago, the five factions lived together in harmony. Then, everything changed when the fire faction attacked.“':'“很久以前，五个阵营和谐共处。然后，一切都在火焰阵营攻击时改变了”',
	'Combo':'连击',
	'Unlock active skills. (Individual skills are unlocked through factioned drawing.)':'“解锁主动技能（单个技能通过阵营抽卡解锁）”',
	'pick-it Premium':'优选尊享版',
	'Unlock the ability to filter upgradeable cards, albeit for a limited time.':'解锁可升级卡牌的筛选功能，尽管是限时的',
	'“You can go right to what you want to see. Nothing to get in your way. pick-it Premium will widen and deepen your card-browsing passions.“':'“你可以直接看到你想看的内容，没有任何阻碍。优选尊享版将拓宽并深化你对卡牌浏览的热情。”',
	
	//卡牌效果
	'No effect.':'无效果',
	'Gain':'每次抽卡获得',
	'points per draw.':'点数',
	'Randomly gain zero to':'每次抽卡随机获得 0 ~',
	'base bulk. Base bulk increase the amount of draws you make at once.':'基础大宗丨基础大宗增加你一次性抽取的次数',
	'bulk power. Bulk power passively generates bulk energy.':'大宗力量丨大宗力量被动生成大宗能量',
	'bulk energy cap. Bulk energy production past the energy cap are slowed down.':'大宗能量上限丨超过能量上限的大宗能量生产将变慢',
	'pack breaking speed.':'卡包拆封速度',
	'cooldown speed.':'冷却速度',
	'Unlock the Marketplace.':'解锁市场',
	'Group together duplicate cards in the draw view, though the compression halves your card revealing speed in the process. Also remove the':'将重复的卡牌在抽卡界面中分组，尽管压缩过程会将卡牌展示速度减半。还会移除',
	'bulk draw limit.':'张大宗抽卡上限',
	'shred multiplier.':'碎片倍率',
	'point multiplier.':'点数倍率',
	'bulk power.':'大宗力量',
	'bulk energy cap.':'大宗能量上限',
	'bulk power, but':'大宗力量，但',
	'bulk power, but':'大宗力量，但',
	'base bulk, but':'基础大宗，但',
	'cooldown duration.':'冷却时间',
	'card multiplier, but':'卡牌倍率，但',
	'cooldown duration and pack breaking duration.':'冷却时间和卡包拆封时间',
	'Unlock the Infobook. View your stats and other things, though with a price...':'解锁信息手册。可查看你的统计数据和其他内容，但需要付出代价...',
	'Raise the level in':'将',
	'\'s effect by':'的效果等级提高',
	'Duplicate cards that are useless are shredded into a new currency called Shreds, including crowned cards and cards with max stars.':'无用的重复卡牌会被粉碎成一种新的货币，叫做碎片，包括加冕卡和已满星的卡牌',
	'fire power per gain.':'每次获取火焰能量',
	'water power per gain.':'每次获取水源能量',
	'leaf power per gain.':'每次获取植物能量',
	'sun power per gain.':'每次获取太阳能量',
	'moon power per gain.':'每次获取月亮能量',
	'card multiplier.':'卡牌倍率',
	'Gain more Points based on the total amount of':'根据你收藏中持有的',
	'cards you have in your collection.':'卡牌的总数量来获得更多点数',
	'(Currently:':'(当前:',
	'cards ⇒':'卡牌 ⇒',
	'crowned cards ⇒':'加冕卡 ⇒',
	'point gain)':'点数增益)',
	'shred gain)':'碎片增益)',
	'fire power, leaf power, and point gains.':'火焰能量、植物能量和点数增益',
	'water power, fire power, and point gains.':'水源能量、火焰能量和点数增益',
	'leaf power, water power, and point gains.':'植物能量、水源能量和点数增益',
	'sun power, moon power, and point gains.':'太阳能量、月亮能量和点数增益',
	'moon power, sun power, and point gains.':'月亮能量、太阳能量和点数增益',
	'Gain more Shreds based on the total amount of crowned cards you have in your collection.':'根据你收藏中持有的加冕卡总数量来获得更多碎片',
	
	//市场
	'Marketplace':'市场',
	
	//剧情
	'I ain\'t reading allat':'我才不看这些呢',
	'Next':'下一页',
	'The year is 2078.':'现在是2078年丨汉化 By LinLei_Baruch',
	'Gacha gaming has become a way of life.':'抽卡游戏已成为一种生活方式。',
	'The thrilling experience of not knowing what items you\'ll get, the satisfying feeling when you get a rare draw, the flexibility and easiness to add gacha mechanics to every game in existence...':'不知道自己会获得什么物品的刺激体验，获得稀有卡牌时的满足感，以及将抽卡机制轻松融入任何游戏的灵活性和便利性……',
	'People have found gacha games to be the best way to pass time, for casual players and the more competitive-minded players alike.':'人们发现抽卡游戏是打发时间的最佳方式，无论是休闲玩家还是更具竞争心态的玩家。',
	'Though, when people talk about gacha games, that\'s not the most significant point to keep in mind.':'不过，当人们谈论抽卡游戏时，这并不是最需要记住的重点。',
	'It\'s the fact that...':'事实是...',
	'They make a':'它们赚了',
	'lot':'很多',
	'of money.':'钱。',
	'The gacha gaming scene has grown into a multi-millillion-dollar worth industry, far greater than any entertainment scene\'s worth, combined.':'抽卡游戏行业已经发展成一个价值数亿美元的产业，远远超过任何娱乐行业的总和。',
	'To chase the money, billions of gacha games are coming out every single blink of an eye.':'为了追逐金钱，数十亿款抽卡游戏在每一眨眼之间层出不穷。',
	'Of course, since the market has become diluted with so many games, they need a way to introduce itself to players and prove that they\'re worth their time.':'当然，由于市场上涌现了如此多的游戏，它们需要一种方式向玩家展示自己，并证明它们值得耗费玩家的时间。',
	'Enter the advertising scene.':'于是，广告行业登场了。',
	'Companies initially advertised their games by showing them good graphics and great gameplay mechanics.':'最初，公司通过展示精美的画面和出色的游戏机制来宣传他们的游戏。',
	'But, that didn\'t seem to attract lots of players.':'但是，这似乎并没有吸引大量玩家。',
	'Eventually, they discovered that the most effective way to market a game is... to just give them lots of free stuff.':'最终，他们发现推广游戏最有效的方式是……给予玩家大量的免费奖励。',
	'After all, virtual currencies and draws are in fact, virtual and can be given as much as the company wants.':'毕竟，虚拟货币和抽卡实际上是虚拟的，可以根据公司需求任意发放。',
	'As players get used to the larger numbers though, as soon as companies know it, players kept asking for more.':'然而，当玩家逐渐习惯了更大的数字时，一旦公司意识到这一点，玩家就开始要求更多了。',
	'Companies can\'t afford to not give more, there will always be a game that decides to give more stuff and thus get more players and money.':'公司无法承受不给予更多奖励的后果，总会有游戏决定提供更多奖励，从而吸引更多玩家和赚取更多钱。',
	'In order to keep up with this, games kept giving more and more free stuff, until the numbers are so inflated they no longer has any real life meaning.':'为了跟上这一趋势，游戏不断提供越来越多的免费奖励，直到这些数字膨胀到不再具有任何现实意义。',
	'You, a person in this society, lying in bed, are about to pick up a new gacha game.':'你，作为这个社会中的一员，正躺在床上，准备开始玩一款新的抽卡游戏。',
	'Omega Cards, for the mobile devices, the first game of its kind to advertise a trillion free card draws. The number that\'s one followed by twelve zeroes.':'《Omega Cards》，一款移动设备上的游戏，首度宣传一万亿次免费抽卡。这个数字后面跟着十二个零。',
	'To people 50 years ago, that sounded like a crazy amount of free draws to give, but the scene has caught up so fast that it\'s now just a lesser number compared to other games.':'对于50年前的人来说，这听起来像是一个疯狂的免费抽卡数量，但这个行业发展得如此迅速，现在它在其他游戏面前已经显得微不足道。',
	'Though, you still see people on the internet come back to it from time to time for the nostalgia values.':'不过，你仍然能在互联网上看到人们时不时地回归这款游戏，寻找那份怀旧的感觉。',
	'You found it interesting enough to start the game for the first time, though the game wants you to use up your one trillion draws first.':'你觉得这款游戏足够有趣，决定第一次开始玩，尽管游戏要求你先使用完一万亿次抽卡次数。',
	'And that\'s when you realize...':'就在这时你意识到……',
	'...you will definitely be here for a while.':'……你肯定会在这里待一段时间。',
	
	//卡包图案
	'TRADING CARD GAME':'集换式卡牌游戏',
	'PACK OF':'本包含有',
	'CARDS':'张卡牌',
	'EDITION':'版本',
    'FIRST':'首个',
	'BONUS ITEMS':'奖励物品',
	'INCLUDED':'包含',
	'© DUDUCAT TRADING CARD GAME CO.':'© DUDUCAT 集换式卡牌游戏公司',
	
	//信息手册
	'Infobook':'信息手册',
	'Statistics':'统计',
	'General':'一般',
	'Time played':'游玩时间',
	'Cards drawn':'已抽取卡牌',
	'Base bulk':'基础大宗',
	'Bulk power':'大宗力量',
	'Card multiplier':'卡牌倍率',
	'appear chance':'出现几率',
	'Base gain':'基础获得',
	'Random gain':'随机获得',
	'Multiplier':'倍率',
	'Gain on draw':'抽卡获得',
	'Crowned card multi':'加冕卡倍率',
	'card multi':'卡倍率',
	'Faction':'阵营',
	'Power chance':'能量几率',
	'Fire Power gain':'火焰能量获得',
	'Water Power gain':'水源能量获得',
	'Leaf Power gain':'植物能量获得',
	'Sun Power gain':'太阳能量获得',
	'Moon Power gain':'月亮能量获得',
	'All Power mult':'全能量倍率',
	
	//信息手册-画廊
	'Gallery':'画廊',
	'Badges':'徽章',
	'Story':'剧情',
	'Intro':'介绍',
	'Badge obtained:':'获得徽章：',
	'(obtained badge)':'（已获得徽章）',
	'(locked badge)':'（未获得徽章）',
	'Another Gacha Game to the Pile':'又一款抽卡游戏加入了这个堆积如山的行列',
	
    // 过滤不需要汉化的文本
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "extra copies": "额外副本",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
	[/^Gain (.+) points per draw.$/, '每次抽卡获得 $1 点数'],
]);